defaults:
  - point

name: Prey

use_privileged_action: true

overlay_color: [0, 1, 0, 1]

instance:
  _target_: cambrian.agents.prey.MjCambrianAgentPrey
  _partial_: true
  speed: -0.75
  # The default target is the next agent in the list
  predator: ${eval:'next((a for a in ${oc.dict.keys:env.agents} if a != "${parent:instance}"), None)'}